In [1]:
# importing data manipulation libraries
import pandas as pd
import numpy as np
# from ydata_profiling import ProfileReport

# importing visualization libraries
import matplotlib.pyplot as plt
import seaborn as sns

# configure notebook for inline plotting
%matplotlib inline

# config pandas to display more than 20 columns
pd.set_option('display.max_columns',250)

# set grid style 
sns.set_style('darkgrid')

In [2]:
# read data retrieved from API
api_data = pd.read_csv('./data/Matches.csv', header=0)

In [3]:
# inspect api data
api_data.head()

,id,homeID,awayID,season,status,roundID,game_week,revised_game_week,homeGoals,awayGoals,homeGoalCount,awayGoalCount,totalGoalCount,team_a_corners,team_b_corners,totalCornerCount,team_a_offsides,team_b_offsides,team_a_yellow_cards,team_b_yellow_cards,team_a_red_cards,team_b_red_cards,team_a_shotsOnTarget,team_b_shotsOnTarget,team_a_shotsOffTarget,team_b_shotsOffTarget,team_a_shots,team_b_shots,team_a_fouls,team_b_fouls,team_a_possession,team_b_possession,refereeID,coach_a_ID,coach_b_ID,stadium_name,stadium_location,team_a_cards_num,team_b_cards_num,odds_ft_1,odds_ft_x,odds_ft_2,odds_ft_over05,odds_ft_over15,odds_ft_over25,odds_ft_over35,odds_ft_over45,odds_ft_under05,odds_ft_under15,odds_ft_under25,odds_ft_under35,odds_ft_under45,odds_btts_yes,odds_btts_no,odds_team_a_cs_yes,odds_team_a_cs_no,odds_team_b_cs_yes,odds_team_b_cs_no,odds_doublechance_1x,odds_doublechance_12,odds_doublechance_x2,odds_1st_half_result_1,odds_1st_half_result_x,odds_1st_half_result_2,odds_2nd_half_result_1,odds_2nd_half_result_x,odds_2nd_half_result_2,odds_dnb_1,odds_dnb_2,odds_corners_over_75,odds_corners_over_85,odds_corners_over_95,odds_corners_over_105,odds_corners_over_115,odds_corners_under_75,odds_corners_under_85,odds_corners_under_95,odds_corners_under_105,odds_corners_under_115,odds_corners_1,odds_corners_x,odds_corners_2,odds_team_to_score_first_1,odds_team_to_score_first_x,odds_team_to_score_first_2,odds_win_to_nil_1,odds_win_to_nil_2,odds_1st_half_over05,odds_1st_half_over15,odds_1st_half_over25,odds_1st_half_over35,odds_1st_half_under05,odds_1st_half_under15,odds_1st_half_under25,odds_1st_half_under35,odds_2nd_half_over05,odds_2nd_half_over15,odds_2nd_half_over25,odds_2nd_half_over35,odds_2nd_half_under05,odds_2nd_half_under15,odds_2nd_half_under25,odds_2nd_half_under35,odds_btts_1st_half_yes,odds_btts_1st_half_no,odds_btts_2nd_half_yes,odds_btts_2nd_half_no,overallGoalCount,ht_goals_team_a,ht_goals_team_b,goals_2hg_team_a,goals_2hg_team_b,GoalCount_2hg,HTGoalCount,date_unix,winningTeam,no_home_away,btts_potential,btts_fhg_potential,btts_2hg_potential,goalTimingDisabled,attendance,corner_timings_recorded,card_timings_recorded,team_a_fh_corners,team_b_fh_corners,team_a_2h_corners,team_b_2h_corners,corner_fh_count,corner_2h_count,team_a_fh_cards,team_b_fh_cards,team_a_2h_cards,team_b_2h_cards,total_fh_cards,total_2h_cards,attacks_recorded,team_a_dangerous_attacks,team_b_dangerous_attacks,team_a_attacks,team_b_attacks,team_a_xg,team_b_xg,total_xg,team_a_penalties_won,team_b_penalties_won,team_a_penalty_goals,team_b_penalty_goals,team_a_penalty_missed,team_b_penalty_missed,pens_recorded,goal_timings_recorded,team_a_0_10_min_goals,team_b_0_10_min_goals,team_a_corners_0_10_min,team_b_corners_0_10_min,team_a_cards_0_10_min,team_b_cards_0_10_min,throwins_recorded,team_a_throwins,team_b_throwins,freekicks_recorded,team_a_freekicks,team_b_freekicks,goalkicks_recorded,team_a_goalkicks,team_b_goalkicks,o45_potential,o35_potential,o25_potential,o15_potential,o05_potential,o15HT_potential,o05HT_potential,o05_2H_potential,o15_2H_potential,corners_potential,offsides_potential,cards_potential,avg_potential,home_url,home_image,home_name,away_url,away_image,away_name,home_ppg,away_ppg,pre_match_home_ppg,pre_match_away_ppg,pre_match_teamA_overall_ppg,pre_match_teamB_overall_ppg,u45_potential,u35_potential,u25_potential,u15_potential,u05_potential,corners_o85_potential,corners_o95_potential,corners_o105_potential,team_a_xg_prematch,team_b_xg_prematch,total_xg_prematch,match_url,competition_id,matches_completed_minimum,over05,over15,over25,over35,over45,over55,btts,homeGoals_timings,awayGoals_timings
0,2155,150,108,2016/2017,complete,19,1,-1,"['45+1', '57']",['47'],2,1,3,5,3,8,1,0,2,2,0,0,4,6,7,9,11,15,7,17,50,50,685.0,196.0,160.0,KCOM Stadium (Hull),NaN,2,2,3.41,3.19,2.39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,3,1,0,1,1,2,1,1471087800,150,0,0,0,0,0,-1,-1,1,-1,-1,-1,-1,-1,-1,0,2,2,0,2,2,-1,0,0,0,0,0.0,0.0,0.0,0,1,0,1,0,0,1,1,0,0,-1,-1,0,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,/clubs/hull-city-afc-150,teams/england-hull-city-afc.png,Hull City,/clubs/leicester-city-fc-108,teams/england-leicester-city-fc.png,Leicester City,1.47,0.53,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,/england/leicester-city-fc-vs-hull-city-afc-h2...,9,38,True,True,True,False,False,False,True,"['45+1', '57']",['47']
1,2156,145,154,2016/2017,complete,19,1,-1,[],['82'],0,1,1,7,4,11,2,2,3,2,0,0,6,8,6,7,12,15,10,14,55,45,688.0,197.0,198.0,Turf Moor (Burnley),NaN,3,2,2.45,3.22,3.26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,1,1,0,1471096800,154,0,0,0,0,0,-1,-1,1,-1,-1,-1,-1,-1,-1,1,0,2,2,1,4,-1,0,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,1,1,0,0,-1,-1,0,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,/clubs/burnley-fc-145,teams/england-burnley-fc.png,Burnley,/clubs/swansea-city-afc-154,teams/wales-swansea-city-afc.png,Swansea City,1.74,0.74,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,/england/burnley-fc-vs-swansea-city-afc-h2h-st...,9,38,True,False,False,False,False,False,False,[],['82']
2,2157,143,142,2016/2017,complete,19,1,-1,[],['74'],0,1,1,3,6,9,0,2,2,2,0,0,7,6,5,6,12,12,12,14,54,46,360.0,199.0,200.0,Selhurst Park (London),NaN,2,2,2.20,3.25,3.80,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,1,0,0,0,1,1,0,1471096800,142,0,0,0,0,0,-1,-1,1,-1,-1,-1,-1,-1,-1,0,1,2,1,1,3,-1,0,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,1,1,0,0,-1,-1,0,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,/clubs/crystal-palace-fc-143,teams/england-crystal-palace-fc.png,Crystal Palace,/clubs/west-bromwich-albion-fc-142,teams/england-west-bromwich-albion-fc.png,West Bromwich Albion,1.05,0.84,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,/england/west-bromwich-albion-fc-vs-crystal-pa...,9,38,True,False,False,False,False,False,False,[],['74']
3,2158,144,92,2016/2017,complete,19,1,-1,['5'],['59'],1,1,2,5,6,11,4,0,0,0,0,0,7,4,3,2,10,6,10,14,41,59,537.0,201.0,156.0,Goodison Park (Liverpool),NaN,0,0,3.13,3.36,2.45,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,2,1,0,0,1,1,1,1471096800,-1,0,0,0,0,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,0,0,0,0,0,0,-1,0,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,1,1,1,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,/clubs/everton-fc-144,teams/england-everton-fc.png,Everton,/clubs/tottenham-hotspur-fc-92,teams/england-tottenham-hotspur-fc.png,Tottenham Hotspur,2.26,1.74,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,/england/tottenham-hotspur-fc-vs-everton-fc-h2...,9,38,True,True,False,False,False,False,True,['5'],['59']
4,2159,147,141,2016/2017,complete,19,1,-1,['11'],['67'],1,1,2,9,6,15,1,3,3,5,0,0,3,2,5,8,8,10,18,13,46,54,693.0,202.0,203.0,Riverside Stadium (Middlesbrough),NaN,3,5,2.49,3.20,3.21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,2,1,0,0,1,1,1,1471096800,-1,0,0,0,0,0,-1,-1,1,-1,-1,-1,-1,-1,-1,2,2,1,3,4,4,-1,0,0,0,0,0.0,0.0,0.0,0,0,0,0,0,0,1,1,0,0,-1,-1,0,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,/clubs/middlesbrough-fc-147,teams/england-middlesbrough-fc.png,Middlesbrough,/clubs/stoke-city-fc-141,teams/england-stoke-city-fc.png,Stoke City,0.95,0.89,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,/england/stoke-city-fc-vs-middlesbrough-fc-h2h...,9,38,True,True,False,False,False,False,True,['11'],['67']

In [4]:
# read scraped data 
scraped_data = pd.read_csv('./data/scraped_match_data.csv', header=0)

In [5]:
# inspect scraped data
scraped_data.head()

,Unnamed: 0,id,title,h_a,xG,xGA,npxG,npxGA,deep,deep_allowed,scored,missed,xpts,result,date,wins,draws,loses,pts,npxGD,ppda.att,ppda.def,ppda_allowed.att,ppda_allowed.def
0,0,71,Aston Villa,a,0.909774,0.423368,0.909774,0.423368,4,3,1,0,1.8322,w,2014-08-16 15:00:00,1,0,0,3,0.486406,323,23,132,32
1,1,71,Aston Villa,h,0.507525,0.699295,0.507525,0.699295,4,7,0,0,1.1057,d,2014-08-23 12:45:00,0,1,0,1,-0.191770,326,21,180,21
2,2,71,Aston Villa,h,0.639316,0.288880,0.639316,0.288880,6,7,2,1,1.6075,w,2014-08-31 13:30:00,1,0,0,3,0.350436,366,13,278,24
3,3,71,Aston Villa,a,0.701676,0.728097,0.701676,0.728097,1,5,1,0,1.3252,w,2014-09-13 17:30:00,1,0,0,3,-0.026421,486,9,91,14
4,4,71,Aston Villa,h,0.649013,1.362240,0.649013,1.362240,0,7,0,3,0.6912,l,2014-09-20 15:00:00,0,0,1,0,-0.713227,531,12,170,22

Before proceeding any further, we should dropped the duplicated index column, named 'Unnamed: 0'

In [6]:
# drop duplicated index column
scraped_data.drop(columns=['Unnamed: 0'], inplace=True)

In [7]:
# confirm duplicated index column has been dropped
scraped_data.head()

,id,title,h_a,xG,xGA,npxG,npxGA,deep,deep_allowed,scored,missed,xpts,result,date,wins,draws,loses,pts,npxGD,ppda.att,ppda.def,ppda_allowed.att,ppda_allowed.def
0,71,Aston Villa,a,0.909774,0.423368,0.909774,0.423368,4,3,1,0,1.8322,w,2014-08-16 15:00:00,1,0,0,3,0.486406,323,23,132,32
1,71,Aston Villa,h,0.507525,0.699295,0.507525,0.699295,4,7,0,0,1.1057,d,2014-08-23 12:45:00,0,1,0,1,-0.191770,326,21,180,21
2,71,Aston Villa,h,0.639316,0.288880,0.639316,0.288880,6,7,2,1,1.6075,w,2014-08-31 13:30:00,1,0,0,3,0.350436,366,13,278,24
3,71,Aston Villa,a,0.701676,0.728097,0.701676,0.728097,1,5,1,0,1.3252,w,2014-09-13 17:30:00,1,0,0,3,-0.026421,486,9,91,14
4,71,Aston Villa,h,0.649013,1.362240,0.649013,1.362240,0,7,0,3,0.6912,l,2014-09-20 15:00:00,0,0,1,0,-0.713227,531,12,170,22

Before proceeding further, it's essential to drop all entries from before the 2014 season from api_data. This step is necessary due to the unavailability of scraped data for those seasons, ensuring a uniform dataset for aggregation.

In [8]:
api_data['season'].unique()

array(['2016/2017', '2015/2016', '2014/2015', '2013/2014', '2017/2018',
       '2012/2013', '2018/2019', '2019/2020', '2011/2012', '2010/2011',
       '2009/2010', '2008/2009', '2007/2008', '2020/2021', '2021/2022',
       '2022/2023', '2023/2024'], dtype=object)

In [9]:
# define list of seasons to drop
seasons_to_drop = ['2013/2014', '2012/2013', '2011/2012', '2010/2011', 
                   '2009/2010', '2008/2009', '2007/2008']

In [10]:
# Filter out rows where the "season" column is in the list
api_data_fil = api_data[~api_data['season'].isin(seasons_to_drop)]

In [11]:
# confirm only relevant season data remains
api_data_fil['season'].unique()

array(['2016/2017', '2015/2016', '2014/2015', '2017/2018', '2018/2019',
       '2019/2020', '2020/2021', '2021/2022', '2022/2023', '2023/2024'],
      dtype=object)

In [12]:
# Group the data by 'homeID' and get unique team names for each group
grouped_data = api_data_fil.groupby('homeID')['home_name'].unique()

# Create a dictionary using zip
# - Explode the nested lists in 'home_name' to individual elements
# - Use zip to pair up each team name with its corresponding 'homeID'
# - Convert the pairs into a dictionary
team_id_mapping = dict(zip(grouped_data.explode(), grouped_data.index))

In [13]:
# view team mappings
print(team_id_mapping)

{'Arsenal': 59, 'Tottenham Hotspur': 92, 'Manchester City': 93, 'Leicester City': 108, 'Stoke City': 141, 'West Bromwich Albion': 142, 'Crystal Palace': 143, 'Everton': 144, 'Burnley': 145, 'Southampton': 146, 'Middlesbrough': 147, 'AFC Bournemouth': 148, 'Manchester United': 149, 'Hull City': 150, 'Liverpool': 151, 'Chelsea': 152, 'West Ham United': 153, 'Swansea City': 154, 'Watford': 155, 'Sunderland': 156, 'Newcastle United': 157, 'Aston Villa': 158, 'Norwich City': 159, 'Queens Park Rangers': 160, 'Cardiff City': 161, 'Fulham': 162, 'Brighton & Hove Albion': 209, 'Nottingham Forest': 211, 'Huddersfield Town': 217, 'Brentford': 218, 'Leeds United': 222, 'Wolverhampton Wanderers': 223, 'Sheffield United': 251, 'Luton Town': 271}

In [14]:
team_names_api_data = list(team_id_mapping.keys())

In [15]:
print(team_names_api_data)

['Arsenal', 'Tottenham Hotspur', 'Manchester City', 'Leicester City', 'Stoke City', 'West Bromwich Albion', 'Crystal Palace', 'Everton', 'Burnley', 'Southampton', 'Middlesbrough', 'AFC Bournemouth', 'Manchester United', 'Hull City', 'Liverpool', 'Chelsea', 'West Ham United', 'Swansea City', 'Watford', 'Sunderland', 'Newcastle United', 'Aston Villa', 'Norwich City', 'Queens Park Rangers', 'Cardiff City', 'Fulham', 'Brighton & Hove Albion', 'Nottingham Forest', 'Huddersfield Town', 'Brentford', 'Leeds United', 'Wolverhampton Wanderers', 'Sheffield United', 'Luton Town']

In [16]:
len(team_names_api_data)

34

In [17]:
team_names_scraped_data = scraped_data['title'].unique()

In [18]:
print(team_names_scraped_data)

['Aston Villa' 'Everton' 'Southampton' 'Leicester' 'West Bromwich Albion'
 'Sunderland' 'Crystal Palace' 'Chelsea' 'West Ham' 'Tottenham' 'Arsenal'
 'Swansea' 'Stoke' 'Newcastle United' 'Liverpool' 'Manchester City'
 'Manchester United' 'Hull' 'Burnley' 'Queens Park Rangers' 'Bournemouth'
 'Norwich' 'Watford' 'Middlesbrough' 'Huddersfield' 'Brighton' 'Cardiff'
 'Fulham' 'Wolverhampton Wanderers' 'Sheffield United' 'Leeds' 'Brentford'
 'Nottingham Forest' 'Luton']

In [19]:
len(team_names_scraped_data)

34

In [20]:
# Get the teams that are in team_names_scraped_data but not in team_names_api_data
teams_not_in_api_data = [team for team in team_names_scraped_data if team not in team_names_api_data]

In [21]:
print(teams_not_in_api_data)

['Leicester', 'West Ham', 'Tottenham', 'Swansea', 'Stoke', 'Hull', 'Bournemouth', 'Norwich', 'Huddersfield', 'Brighton', 'Cardiff', 'Leeds', 'Luton']

### Harmonizing naming conventions

In [22]:
# Define a dictionary that maps original team names to their corresponding new names in the scraped_data 
names = {'Leicester': 'Leicester City', 'West Ham': 'West Ham United', 
         'Tottenham': 'Tottenham Hotspur', 'Swansea':'Swansea City', 
         'Stoke': 'Stoke City', 'Hull': 'Hull City', 'Bournemouth': 'AFC Bournemouth',
         'Norwich':'Norwich City', 'Huddersfield':'Huddersfield Town', 'Brighton':'Brighton & Hove Albion', 
         'Cardiff':'Cardiff City', 'Leeds': 'Leeds United', 'Luton':'Luton Town'}

In [23]:
# Replace names in the 'title' column
scraped_data['title'].replace(names, inplace=True)

In [24]:
# redefine team_names variable for scraped data
team_names_scraped_data = scraped_data['title'].unique()

In [25]:
# confirm renaming worked as planned
teams_not_in_api_data = [team for team in team_names_scraped_data if team not in team_names_api_data]

# there should be no naming mismatches
print(teams_not_in_api_data)

[]

## harmonize team_id columns
- Here we will adopt the team_ids from the api_data in the scraped_data dataframe

In [26]:
# Map team names to their corresponding teamID using the team_id_mapping dictionary
scraped_data['teamID'] = scraped_data['title'].map(team_id_mapping)

In [27]:
scraped_data.drop(columns=['id'], inplace=True)

In [28]:
scraped_data.head()

,title,h_a,xG,xGA,npxG,npxGA,deep,deep_allowed,scored,missed,xpts,result,date,wins,draws,loses,pts,npxGD,ppda.att,ppda.def,ppda_allowed.att,ppda_allowed.def,teamID
0,Aston Villa,a,0.909774,0.423368,0.909774,0.423368,4,3,1,0,1.8322,w,2014-08-16 15:00:00,1,0,0,3,0.486406,323,23,132,32,158
1,Aston Villa,h,0.507525,0.699295,0.507525,0.699295,4,7,0,0,1.1057,d,2014-08-23 12:45:00,0,1,0,1,-0.191770,326,21,180,21,158
2,Aston Villa,h,0.639316,0.288880,0.639316,0.288880,6,7,2,1,1.6075,w,2014-08-31 13:30:00,1,0,0,3,0.350436,366,13,278,24,158
3,Aston Villa,a,0.701676,0.728097,0.701676,0.728097,1,5,1,0,1.3252,w,2014-09-13 17:30:00,1,0,0,3,-0.026421,486,9,91,14,158
4,Aston Villa,h,0.649013,1.362240,0.649013,1.362240,0,7,0,3,0.6912,l,2014-09-20 15:00:00,0,0,1,0,-0.713227,531,12,170,22,158

In [29]:
# Reorder columns with 'teamID' as the first column
scraped_data = scraped_data[['teamID', 'title', 'h_a', 'xG', 'xGA', 'npxG', 'npxGA', 'deep', 'deep_allowed',
                             'scored', 'missed', 'xpts', 'result', 'date', 'wins', 'draws', 'loses',
                             'pts', 'npxGD', 'ppda.att', 'ppda.def', 'ppda_allowed.att',
                             'ppda_allowed.def']]

In [30]:
scraped_data.head()

,teamID,title,h_a,xG,xGA,npxG,npxGA,deep,deep_allowed,scored,missed,xpts,result,date,wins,draws,loses,pts,npxGD,ppda.att,ppda.def,ppda_allowed.att,ppda_allowed.def
0,158,Aston Villa,a,0.909774,0.423368,0.909774,0.423368,4,3,1,0,1.8322,w,2014-08-16 15:00:00,1,0,0,3,0.486406,323,23,132,32
1,158,Aston Villa,h,0.507525,0.699295,0.507525,0.699295,4,7,0,0,1.1057,d,2014-08-23 12:45:00,0,1,0,1,-0.191770,326,21,180,21
2,158,Aston Villa,h,0.639316,0.288880,0.639316,0.288880,6,7,2,1,1.6075,w,2014-08-31 13:30:00,1,0,0,3,0.350436,366,13,278,24
3,158,Aston Villa,a,0.701676,0.728097,0.701676,0.728097,1,5,1,0,1.3252,w,2014-09-13 17:30:00,1,0,0,3,-0.026421,486,9,91,14
4,158,Aston Villa,h,0.649013,1.362240,0.649013,1.362240,0,7,0,3,0.6912,l,2014-09-20 15:00:00,0,0,1,0,-0.713227,531,12,170,22

### harmonize data columns

In [31]:
scraped_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7246 entries, 0 to 7245
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   teamID            7246 non-null   int64
 1   title             7246 non-null   object
 2   h_a               7246 non-null   object
 3   xG                7246 non-null   float64
 4   xGA               7246 non-null   float64
 5   npxG              7246 non-null   float64
 6   npxGA             7246 non-null   float64
 7   deep              7246 non-null   int64
 8   deep_allowed      7246 non-null   int64
 9   scored            7246 non-null   int64
 10  missed            7246 non-null   int64
 11  xpts              7246 non-null   float64
 12  result            7246 non-null   object
 13  date              7246 non-null   object
 14  wins              7246 non-null   int64
 15  draws             7246 non-null   int64
 16  loses             7246 non-null   int64
 17  pts               7246 non-null   int64
 18  npxGD             7246 non-null   float64
 19  ppda.att          7246 non-null   int64
 20  ppda.def          7246 non-null   int64
 21  ppda_allowed.att  7246 non-null   int64
 22  ppda_allowed.def  7246 non-null   int64
dtypes: float64(6), int64(13), object(4)
memory usage: 1.3+ MB

The date column was read as object instead of datetime, let's fix this.

In [32]:
# Convert 'date' column to datetime format
scraped_data['date'] = pd.to_datetime(scraped_data['date'])

In [33]:
# Extract the date part from the 'date' column
scraped_data['date'] = scraped_data['date'].dt.date

In [34]:
scraped_data[['date']].head()

         date
0  2014-08-16
1  2014-08-23
2  2014-08-31
3  2014-09-13
4  2014-09-20

In [35]:
# Convert the 'date_unix' column to datetime
api_data['date_unix'] = pd.to_datetime(api_data['date_unix'], unit='s')

In [36]:
api_data['date'] = api_data['date_unix'].dt.date

In [37]:
api_data[['date']].head()

         date
0  2016-08-13
1  2016-08-13
2  2016-08-13
3  2016-08-13
4  2016-08-13

### Data Aggregation:
With naming and date harmonization complete, we can now work on aggregating the two dataframes. We need only a few columns from the api_dataframe, we can drop the other columns.

In [38]:
# Keep only the specified columns in the api_data DataFrame
api_data_subset = api_data[['id', 'homeID','awayID', 'home_name', 'away_name', 'date', 'season', 'status', 'homeGoalCount', 'awayGoalCount',
                            'totalGoalCount', 'team_a_cards_num', 'team_b_cards_num', 'odds_ft_1', 'odds_ft_x',
                            'odds_ft_2', 'home_ppg', 'away_ppg', 'team_a_xg_prematch', 'team_b_xg_prematch',
                            'total_xg_prematch', ]]

In [39]:
api_data_subset.head()

,id,homeID,awayID,home_name,away_name,date,season,status,homeGoalCount,awayGoalCount,totalGoalCount,team_a_cards_num,team_b_cards_num,odds_ft_1,odds_ft_x,odds_ft_2,home_ppg,away_ppg,team_a_xg_prematch,team_b_xg_prematch,total_xg_prematch
0,2155,150,108,Hull City,Leicester City,2016-08-13,2016/2017,complete,2,1,3,2,2,3.41,3.19,2.39,1.47,0.53,0.0,0.0,0.0
1,2156,145,154,Burnley,Swansea City,2016-08-13,2016/2017,complete,0,1,1,3,2,2.45,3.22,3.26,1.74,0.74,0.0,0.0,0.0
2,2157,143,142,Crystal Palace,West Bromwich Albion,2016-08-13,2016/2017,complete,0,1,1,2,2,2.20,3.25,3.80,1.05,0.84,0.0,0.0,0.0
3,2158,144,92,Everton,Tottenham Hotspur,2016-08-13,2016/2017,complete,1,1,2,0,0,3.13,3.36,2.45,2.26,1.74,0.0,0.0,0.0
4,2159,147,141,Middlesbrough,Stoke City,2016-08-13,2016/2017,complete,1,1,2,3,5,2.49,3.20,3.21,0.95,0.89,0.0,0.0,0.0

In [40]:
# Define a list of features from the 'scraped_data' dataframe to include in the merged dataframe
scraped_data_feats = ['xG', 'xGA', 'npxG', 'npxGA', 'deep', 'deep_allowed', 'scored', 'missed', 
                      'xpts', 'npxGD', 'ppda.att', 'ppda.def', 'ppda_allowed.att', 'ppda_allowed.def']

In [41]:
home_id = 150

# Convert the date string to a datetime object
date = pd.to_datetime('2016-08-13').date()

In [42]:
# Sort the DataFrame by the 'date' column in ascending order
sorted_scraped_data = scraped_data.sort_values(by='date', ascending=False)

In [43]:
result = sorted_scraped_data[(sorted_scraped_data['teamID'] == home_id) & (sorted_scraped_data['date'] < date)].head().describe().loc['mean']

In [44]:
result

teamID              150.000000
xG                    0.890168
xGA                   1.357364
npxG                  0.890168
npxGA                 1.357364
deep                  3.000000
deep_allowed          9.000000
scored                0.400000
missed                1.200000
xpts                  1.137760
wins                  0.200000
draws                 0.200000
loses                 0.600000
pts                   0.800000
npxGD                -0.467196
ppda.att            319.400000
ppda.def             21.800000
ppda_allowed.att    174.600000
ppda_allowed.def     22.400000
Name: mean, dtype: float64

In [45]:
result_dict = result.to_dict()

In [46]:
result_dict

{'teamID': 150.0,
 'xG': 0.8901679999999998,
 'xGA': 1.3573638000000003,
 'npxG': 0.8901679999999998,
 'npxGA': 1.3573638000000003,
 'deep': 3.0,
 'deep_allowed': 9.0,
 'scored': 0.4,
 'missed': 1.2,
 'xpts': 1.13776,
 'wins': 0.2,
 'draws': 0.2,
 'loses': 0.6,
 'pts': 0.8,
 'npxGD': -0.4671958000000001,
 'ppda.att': 319.4,
 'ppda.def': 21.8,
 'ppda_allowed.att': 174.6,
 'ppda_allowed.def': 22.4}

In [47]:
# {key+ f'_home':value for key, value in filtered_result_dict[0].items() }

In [48]:
# Create empty columns for home and away features
for feat in scraped_data_feats:
    api_data_subset.loc[:, f'{feat}_home'] = None
    api_data_subset.loc[:, f'{feat}_away'] = None

C:\Users\user\AppData\Local\Temp\ipykernel_18216\932496461.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset.loc[:, f'{feat}_home'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_18216\932496461.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset.loc[:, f'{feat}_away'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_18216\932496461.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset.loc[:, f'{feat}_home'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_18216\932496461.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset.loc[:, f'{feat}_away'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_18216\932496461.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset.loc[:, f'{feat}_home'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_18216\932496461.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset.loc[:, f'{feat}_away'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_18216\932496461.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset.loc[:, f'{feat}_home'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_18216\932496461.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset.loc[:, f'{feat}_away'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_18216\932496461.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset.loc[:, f'{feat}_home'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_18216\932496461.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset.loc[:, f'{feat}_away'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_18216\932496461.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset.loc[:, f'{feat}_home'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_18216\932496461.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset.loc[:, f'{feat}_away'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_18216\932496461.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset.loc[:, f'{feat}_home'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_18216\932496461.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset.loc[:, f'{feat}_away'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_18216\932496461.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset.loc[:, f'{feat}_home'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_18216\932496461.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset.loc[:, f'{feat}_away'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_18216\932496461.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset.loc[:, f'{feat}_home'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_18216\932496461.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset.loc[:, f'{feat}_away'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_18216\932496461.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset.loc[:, f'{feat}_home'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_18216\932496461.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset.loc[:, f'{feat}_away'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_18216\932496461.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset.loc[:, f'{feat}_home'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_18216\932496461.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset.loc[:, f'{feat}_away'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_18216\932496461.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset.loc[:, f'{feat}_home'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_18216\932496461.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset.loc[:, f'{feat}_away'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_18216\932496461.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset.loc[:, f'{feat}_home'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_18216\932496461.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset.loc[:, f'{feat}_away'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_18216\932496461.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset.loc[:, f'{feat}_home'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_18216\932496461.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset.loc[:, f'{feat}_away'] = None

In [49]:
api_data_subset.head()

,id,homeID,awayID,home_name,away_name,date,season,status,homeGoalCount,awayGoalCount,totalGoalCount,team_a_cards_num,team_b_cards_num,odds_ft_1,odds_ft_x,odds_ft_2,home_ppg,away_ppg,team_a_xg_prematch,team_b_xg_prematch,total_xg_prematch,xG_home,xG_away,xGA_home,xGA_away,npxG_home,npxG_away,npxGA_home,npxGA_away,deep_home,deep_away,deep_allowed_home,deep_allowed_away,scored_home,scored_away,missed_home,missed_away,xpts_home,xpts_away,npxGD_home,npxGD_away,ppda.att_home,ppda.att_away,ppda.def_home,ppda.def_away,ppda_allowed.att_home,ppda_allowed.att_away,ppda_allowed.def_home,ppda_allowed.def_away
0,2155,150,108,Hull City,Leicester City,2016-08-13,2016/2017,complete,2,1,3,2,2,3.41,3.19,2.39,1.47,0.53,0.0,0.0,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1,2156,145,154,Burnley,Swansea City,2016-08-13,2016/2017,complete,0,1,1,3,2,2.45,3.22,3.26,1.74,0.74,0.0,0.0,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2,2157,143,142,Crystal Palace,West Bromwich Albion,2016-08-13,2016/2017,complete,0,1,1,2,2,2.20,3.25,3.80,1.05,0.84,0.0,0.0,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3,2158,144,92,Everton,Tottenham Hotspur,2016-08-13,2016/2017,complete,1,1,2,0,0,3.13,3.36,2.45,2.26,1.74,0.0,0.0,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
4,2159,147,141,Middlesbrough,Stoke City,2016-08-13,2016/2017,complete,1,1,2,3,5,2.49,3.20,3.21,0.95,0.89,0.0,0.0,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

In [50]:
# Iterate through each row in api_data_subset
for index, row in api_data_subset.iterrows():
    home_id = row['homeID']
    game_date = row['date']
    
    # Retrieve stats from scraped_data dataframe
    result = sorted_scraped_data[(sorted_scraped_data['teamID'] == home_id) & (sorted_scraped_data['date'] < date)]
    # get mean for each statistics for the last  5 games before current match
    result_mean = result.head(15).describe().loc['mean']
    # Check if there are matching records
    if not result.empty:
        # Take the first matching record
        filtered_result_dict = result_mean.to_dict()
        
        # Filter out irrelevant columns from result
        filtered_result_dict = {key: value for key, value in filtered_result_dict.items() if key in scraped_data_feats}
        
        # Update values in the dataframe
        for key, value in filtered_result_dict.items():
            api_data_subset.at[index, f'{key}_home'] = value

In [51]:
# Iterate through each row in api_data_subset
for index, row in api_data_subset.iterrows():
    away_id = row['awayID']
    game_date = row['date']

    
    # Retrieve stats from scraped_data dataframe
    result = sorted_scraped_data[(sorted_scraped_data['teamID'] == away_id) & (sorted_scraped_data['date'] < game_date)]
    # get mean for each statistics for the last  5 games before current match
    result_mean = result.head(15).describe().loc['mean']
       
    # Check if there are matching records
    if not result.empty:
        # Take the first matching record
        filtered_result_dict = result_mean.to_dict()
        
        # Filter out irrelevant columns from result
        filtered_result_dict = {key: value for key, value in filtered_result_dict.items() if key in scraped_data_feats}
        
        # Update values in the dataframe
        for key, value in filtered_result_dict.items():
            api_data_subset.at[index, f'{key}_away'] = value

In [52]:
# Inspect the resulting dataframe
api_data_subset.head()

,id,homeID,awayID,home_name,away_name,date,season,status,homeGoalCount,awayGoalCount,totalGoalCount,team_a_cards_num,team_b_cards_num,odds_ft_1,odds_ft_x,odds_ft_2,home_ppg,away_ppg,team_a_xg_prematch,team_b_xg_prematch,total_xg_prematch,xG_home,xG_away,xGA_home,xGA_away,npxG_home,npxG_away,npxGA_home,npxGA_away,deep_home,deep_away,deep_allowed_home,deep_allowed_away,scored_home,scored_away,missed_home,missed_away,xpts_home,xpts_away,npxGD_home,npxGD_away,ppda.att_home,ppda.att_away,ppda.def_home,ppda.def_away,ppda_allowed.att_home,ppda_allowed.att_away,ppda_allowed.def_home,ppda_allowed.def_away
0,2155,150,108,Hull City,Leicester City,2016-08-13,2016/2017,complete,2,1,3,2,2,3.41,3.19,2.39,1.47,0.53,0.0,0.0,0.0,1.053772,1.976917,1.10703,1.128482,1.053772,1.773939,1.056286,1.026993,3.933333,6.333333,7.2,8.533333,0.866667,1.733333,1.2,0.666667,1.386147,1.923433,-0.002514,0.746946,280.333333,238.133333,20.133333,25.733333,185.066667,168.266667,20.933333,22.666667
1,2156,145,154,Burnley,Swansea City,2016-08-13,2016/2017,complete,0,1,1,3,2,2.45,3.22,3.26,1.74,0.74,0.0,0.0,0.0,0.982456,1.12589,1.571102,1.606961,0.931711,1.12589,1.418868,1.606961,5.733333,5.733333,6.666667,7.4,0.466667,1.333333,1.0,1.4,0.958993,1.077167,-0.487157,-0.481071,274.466667,217.933333,23.6,28.0,179.533333,256.466667,20.266667,26.333333
2,2157,143,142,Crystal Palace,West Bromwich Albion,2016-08-13,2016/2017,complete,0,1,1,2,2,2.20,3.25,3.80,1.05,0.84,0.0,0.0,0.0,1.11155,1.211611,1.430625,1.335043,1.060806,1.058202,1.278391,1.284298,3.733333,4.466667,8.733333,7.8,1.0,0.8,1.6,1.2,1.137407,1.299807,-0.217585,-0.226096,208.266667,260.933333,23.866667,24.466667,182.666667,137.866667,24.866667,21.866667
3,2158,144,92,Everton,Tottenham Hotspur,2016-08-13,2016/2017,complete,1,1,2,0,0,3.13,3.36,2.45,2.26,1.74,0.0,0.0,0.0,1.469059,1.948587,1.613283,1.014782,1.215339,1.8471,1.511794,0.964038,6.466667,7.333333,9.666667,4.733333,1.266667,1.866667,1.4,1.066667,1.350113,2.020447,-0.296455,0.883062,208.533333,169.133333,21.8,26.6,250.666667,270.6,24.8,24.266667
4,2159,147,141,Middlesbrough,Stoke City,2016-08-13,2016/2017,complete,1,1,2,3,5,2.49,3.20,3.21,0.95,0.89,0.0,0.0,0.0,None,0.959606,None,1.577794,None,0.908862,None,1.425562,None,5.733333,None,6.266667,None,1.133333,None,2.0,None,1.061133,None,-0.516701,None,221.8,None,22.866667,None,241.0,None,25.066667

In [53]:
api_data_subset.shape

(6460, 49)

In [54]:
api_data_subset[(api_data_subset['date'] == date)]

,id,homeID,awayID,home_name,away_name,date,season,status,homeGoalCount,awayGoalCount,totalGoalCount,team_a_cards_num,team_b_cards_num,odds_ft_1,odds_ft_x,odds_ft_2,home_ppg,away_ppg,team_a_xg_prematch,team_b_xg_prematch,total_xg_prematch,xG_home,xG_away,xGA_home,xGA_away,npxG_home,npxG_away,npxGA_home,npxGA_away,deep_home,deep_away,deep_allowed_home,deep_allowed_away,scored_home,scored_away,missed_home,missed_away,xpts_home,xpts_away,npxGD_home,npxGD_away,ppda.att_home,ppda.att_away,ppda.def_home,ppda.def_away,ppda_allowed.att_home,ppda_allowed.att_away,ppda_allowed.def_home,ppda_allowed.def_away
0,2155,150,108,Hull City,Leicester City,2016-08-13,2016/2017,complete,2,1,3,2,2,3.41,3.19,2.39,1.47,0.53,0.0,0.0,0.0,1.053772,1.976917,1.10703,1.128482,1.053772,1.773939,1.056286,1.026993,3.933333,6.333333,7.2,8.533333,0.866667,1.733333,1.2,0.666667,1.386147,1.923433,-0.002514,0.746946,280.333333,238.133333,20.133333,25.733333,185.066667,168.266667,20.933333,22.666667
1,2156,145,154,Burnley,Swansea City,2016-08-13,2016/2017,complete,0,1,1,3,2,2.45,3.22,3.26,1.74,0.74,0.0,0.0,0.0,0.982456,1.12589,1.571102,1.606961,0.931711,1.12589,1.418868,1.606961,5.733333,5.733333,6.666667,7.4,0.466667,1.333333,1.0,1.4,0.958993,1.077167,-0.487157,-0.481071,274.466667,217.933333,23.6,28.0,179.533333,256.466667,20.266667,26.333333
2,2157,143,142,Crystal Palace,West Bromwich Albion,2016-08-13,2016/2017,complete,0,1,1,2,2,2.20,3.25,3.80,1.05,0.84,0.0,0.0,0.0,1.11155,1.211611,1.430625,1.335043,1.060806,1.058202,1.278391,1.284298,3.733333,4.466667,8.733333,7.8,1.0,0.8,1.6,1.2,1.137407,1.299807,-0.217585,-0.226096,208.266667,260.933333,23.866667,24.466667,182.666667,137.866667,24.866667,21.866667
3,2158,144,92,Everton,Tottenham Hotspur,2016-08-13,2016/2017,complete,1,1,2,0,0,3.13,3.36,2.45,2.26,1.74,0.0,0.0,0.0,1.469059,1.948587,1.613283,1.014782,1.215339,1.8471,1.511794,0.964038,6.466667,7.333333,9.666667,4.733333,1.266667,1.866667,1.4,1.066667,1.350113,2.020447,-0.296455,0.883062,208.533333,169.133333,21.8,26.6,250.666667,270.6,24.8,24.266667
4,2159,147,141,Middlesbrough,Stoke City,2016-08-13,2016/2017,complete,1,1,2,3,5,2.49,3.20,3.21,0.95,0.89,0.0,0.0,0.0,None,0.959606,None,1.577794,None,0.908862,None,1.425562,None,5.733333,None,6.266667,None,1.133333,None,2.0,None,1.061133,None,-0.516701,None,221.8,None,22.866667,None,241.0,None,25.066667
5,2160,146,155,Southampton,Watford,2016-08-13,2016/2017,complete,1,1,2,1,4,1.80,3.64,5.13,1.26,0.63,0.0,0.0,0.0,1.541624,1.057258,1.269699,1.732613,1.435341,0.905024,1.269699,1.528459,8.6,5.466667,5.8,7.266667,1.8,0.866667,1.133333,1.6,1.5882,0.991227,0.165642,-0.623435,238.533333,241.066667,25.933333,27.266667,190.266667,188.866667,20.066667,25.8
6,2161,93,156,Manchester City,Sunderland,2016-08-13,2016/2017,complete,2,1,3,1,2,1.21,7.00,9.99,2.11,0.53,0.0,0.0,0.0,1.466291,1.171354,1.029806,1.155271,1.263313,1.069865,0.979063,1.104526,9.4,5.466667,3.666667,9.066667,1.733333,1.333333,1.2,1.066667,1.63854,1.40322,0.284249,-0.034661,216.2,238.466667,27.466667,23.933333,263.266667,141.4,26.266667,21.0

In [55]:
api_data_subset.to_csv('./data/match_data_avg_stats.csv', index=False)