In [1]:
# importing data manipulation libraries
import pandas as pd
import numpy as np
# from ydata_profiling import ProfileReport

# importing visualization libraries
import matplotlib.pyplot as plt
import seaborn as sns

# configure notebook for inline plotting
%matplotlib inline

# config pandas to display more than 20 columns
pd.set_option('display.max_columns',250)

# set grid style 
sns.set_style('darkgrid')

In [2]:
# read testing data retrieved from API
api_data = pd.read_csv('./data/api_testing_data.csv', header=0)

In [3]:
# inspect api testing data
api_data.head()

,id,homeID,awayID,season,status,roundID,game_week,revised_game_week,homeGoals,awayGoals,homeGoalCount,awayGoalCount,totalGoalCount,team_a_corners,team_b_corners,totalCornerCount,team_a_offsides,team_b_offsides,team_a_yellow_cards,team_b_yellow_cards,team_a_red_cards,team_b_red_cards,team_a_shotsOnTarget,team_b_shotsOnTarget,team_a_shotsOffTarget,team_b_shotsOffTarget,team_a_shots,team_b_shots,team_a_fouls,team_b_fouls,team_a_possession,team_b_possession,refereeID,coach_a_ID,coach_b_ID,stadium_name,stadium_location,team_a_cards_num,team_b_cards_num,odds_ft_1,odds_ft_x,odds_ft_2,odds_ft_over05,odds_ft_over15,odds_ft_over25,odds_ft_over35,odds_ft_over45,odds_ft_under05,odds_ft_under15,odds_ft_under25,odds_ft_under35,odds_ft_under45,odds_btts_yes,odds_btts_no,odds_team_a_cs_yes,odds_team_a_cs_no,odds_team_b_cs_yes,odds_team_b_cs_no,odds_doublechance_1x,odds_doublechance_12,odds_doublechance_x2,odds_1st_half_result_1,odds_1st_half_result_x,odds_1st_half_result_2,odds_2nd_half_result_1,odds_2nd_half_result_x,odds_2nd_half_result_2,odds_dnb_1,odds_dnb_2,odds_corners_over_75,odds_corners_over_85,odds_corners_over_95,odds_corners_over_105,odds_corners_over_115,odds_corners_under_75,odds_corners_under_85,odds_corners_under_95,odds_corners_under_105,odds_corners_under_115,odds_corners_1,odds_corners_x,odds_corners_2,odds_team_to_score_first_1,odds_team_to_score_first_x,odds_team_to_score_first_2,odds_win_to_nil_1,odds_win_to_nil_2,odds_1st_half_over05,odds_1st_half_over15,odds_1st_half_over25,odds_1st_half_over35,odds_1st_half_under05,odds_1st_half_under15,odds_1st_half_under25,odds_1st_half_under35,odds_2nd_half_over05,odds_2nd_half_over15,odds_2nd_half_over25,odds_2nd_half_over35,odds_2nd_half_under05,odds_2nd_half_under15,odds_2nd_half_under25,odds_2nd_half_under35,odds_btts_1st_half_yes,odds_btts_1st_half_no,odds_btts_2nd_half_yes,odds_btts_2nd_half_no,overallGoalCount,ht_goals_team_a,ht_goals_team_b,goals_2hg_team_a,goals_2hg_team_b,GoalCount_2hg,HTGoalCount,date_unix,winningTeam,no_home_away,btts_potential,btts_fhg_potential,btts_2hg_potential,goalTimingDisabled,attendance,corner_timings_recorded,card_timings_recorded,team_a_fh_corners,team_b_fh_corners,team_a_2h_corners,team_b_2h_corners,corner_fh_count,corner_2h_count,team_a_fh_cards,team_b_fh_cards,team_a_2h_cards,team_b_2h_cards,total_fh_cards,total_2h_cards,attacks_recorded,team_a_dangerous_attacks,team_b_dangerous_attacks,team_a_attacks,team_b_attacks,team_a_xg,team_b_xg,total_xg,team_a_penalties_won,team_b_penalties_won,team_a_penalty_goals,team_b_penalty_goals,team_a_penalty_missed,team_b_penalty_missed,pens_recorded,goal_timings_recorded,team_a_0_10_min_goals,team_b_0_10_min_goals,team_a_corners_0_10_min,team_b_corners_0_10_min,team_a_cards_0_10_min,team_b_cards_0_10_min,throwins_recorded,team_a_throwins,team_b_throwins,freekicks_recorded,team_a_freekicks,team_b_freekicks,goalkicks_recorded,team_a_goalkicks,team_b_goalkicks,o45_potential,o35_potential,o25_potential,o15_potential,o05_potential,o15HT_potential,o05HT_potential,o05_2H_potential,o15_2H_potential,corners_potential,offsides_potential,cards_potential,avg_potential,home_url,home_image,home_name,away_url,away_image,away_name,home_ppg,away_ppg,pre_match_home_ppg,pre_match_away_ppg,pre_match_teamA_overall_ppg,pre_match_teamB_overall_ppg,u45_potential,u35_potential,u25_potential,u15_potential,u05_potential,corners_o85_potential,corners_o95_potential,corners_o105_potential,team_a_xg_prematch,team_b_xg_prematch,total_xg_prematch,match_url,competition_id,matches_completed_minimum,over05,over15,over25,over35,over45,over55,btts,homeGoals_timings,awayGoals_timings
0,6688951,145,93,2023/2024,complete,100543,1,-1,[],"['4', '36', '75']",0,3,3,6,5,11,0,1,0,0,1,0,2,9,3,4,5,13,11,8,34,66,360.0,36439,72,Turf Moor (Burnley),NaN,2,0,11.00,6.30,1.28,1.02,1.20,1.56,2.65,4.85,17.0,4.85,2.50,1.51,1.20,2.05,1.70,7.75,1.07,1.85,1.83,3.40,1.15,1.06,8.00,2.60,1.80,7.00,3.00,1.57,0,0,1.33,1.58,1.98,2.55,3.45,2.88,2.16,1.71,1.42,1.23,3.45,8.5,1.43,4.33,16.75,1.22,15.00,2.0,1.30,2.38,6.0,17,3.40,1.53,1.13,1.03,1.18,1.83,3.75,10.0,4.5,1.83,1.25,1.06,0,0,0,0,3,0,2,0,1,1,2,1691780400,93,0,0,0,0,0,21572,1,1,1,1,5,4,2,9,0,0,1,0,0,1,1,25,36,81,102,0.65,1.72,2.37,0,0,0,0,0,0,1,1,0,1,0,1,0,0,1,15,13,1,9,11,1,5,7,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,/clubs/burnley-fc-145,teams/england-burnley-fc.png,Burnley,/clubs/manchester-city-fc-93,teams/england-manchester-city-fc.png,Manchester City,0.36,2.00,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,/england/manchester-city-fc-vs-burnley-fc-h2h-...,9660,20,True,True,True,False,False,False,False,[],"['4', '36', '75']"
1,6688952,59,211,2023/2024,complete,100543,1,-1,"['26', '32']",['82'],2,1,3,8,3,11,2,1,2,2,0,0,8,3,3,3,11,6,12,12,78,22,393.0,33237,29453,Emirates Stadium (London),NaN,2,2,1.25,6.25,9.50,1.02,1.11,1.45,2.01,3.45,23.0,6.50,2.70,1.80,1.30,2.00,1.75,1.88,1.80,10.00,1.05,1.06,1.12,4.61,1.57,2.88,9.50,1.40,3.60,8.50,0,0,1.17,1.32,1.56,1.91,2.35,4.10,2.90,2.20,1.78,1.48,1.14,14.0,8.00,1.17,26.00,4.75,1.95,19.0,1.22,2.10,4.5,13,4.00,1.67,1.18,1.04,1.13,1.67,3.00,6.5,6.0,2.10,1.36,1.11,0,0,0,0,3,2,0,0,1,1,2,1691841600,59,0,0,0,0,0,59984,1,1,5,0,3,3,5,6,1,1,1,1,2,2,1,63,23,130,50,1.72,0.76,2.48,0,0,0,0,0,0,1,1,0,0,2,0,0,0,1,18,9,1,14,14,1,8,5,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,/clubs/arsenal-fc-59,teams/england-arsenal-fc.png,Arsenal,/clubs/nottingham-forest-fc-211,teams/england-nottingham-forest-fc.png,Nottingham Forest,2.36,0.73,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,/england/arsenal-fc-vs-nottingham-forest-fc-h2...,9660,21,True,True,True,False,False,False,True,"['26', '32']",['82']
2,6688953,148,153,2023/2024,complete,100543,1,-1,['82'],['51'],1,1,2,10,4,14,0,2,1,4,0,0,6,4,7,9,13,13,8,14,63,37,728.0,11572,206,"Vitality Stadium (Bournemouth, Dorset)",NaN,1,4,2.63,3.06,2.35,1.05,1.29,1.89,3.00,5.75,9.0,3.50,1.99,1.36,1.13,1.70,2.05,3.40,1.28,3.25,1.30,1.49,1.30,1.46,3.25,2.20,3.20,2.88,2.38,2.75,0,0,1.19,1.36,1.62,2.00,2.60,3.90,2.75,2.12,1.68,1.40,2.08,8.0,1.96,2.05,9.00,1.83,4.60,4.4,1.36,2.75,8.0,21,3.00,1.40,1.08,1.02,1.22,2.00,4.33,11.0,4.0,1.73,1.20,1.05,0,0,0,0,2,0,0,1,1,2,0,1691848800,-1,0,0,0,0,0,-1,1,1,4,3,6,1,7,7,0,1,1,3,1,4,1,57,40,117,86,1.66,1.39,3.05,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,21,22,-1,-1,-1,1,8,12,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,/clubs/afc-bournemouth-148,teams/england-afc-bournemouth.png,AFC Bournemouth,/clubs/west-ham-united-fc-153,teams/england-west-ham-united-fc.png,West Ham United,1.33,1.60,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,/england/afc-bournemouth-vs-west-ham-united-fc...,9660,19,True,True,False,False,False,False,True,['82'],['51']
3,6688954,209,271,2023/2024,complete,100543,1,-1,"['36', '71', '85', '90+5']",['81'],4,1,5,6,7,13,2,3,2,2,0,0,13,4,10,4,23,8,4,8,71,29,721.0,1084,417,The American Express Community Stadium (Falmer...,NaN,2,2,1.34,4.70,7.00,1.02,1.18,1.58,2.38,4.90,14.0,4.80,2.29,1.57,1.17,2.00,1.75,1.85,1.82,7.50,1.08,1.08,1.17,3.63,1.80,2.60,8.00,1.57,3.10,7.00,0,0,1.22,1.42,1.72,2.15,2.75,3.50,2.55,1.98,1.60,1.36,1.21,11.5,6.00,1.22,19.00,4.33,2.00,15.0,1.30,2.38,6.0,17,3.40,1.53,1.13,1.03,1.17,1.83,3.75,9.0,5.0,1.83,1.25,1.07,0,0,0,0,5,1,0,3,1,4,1,1691848800,209,0,0,0,0,0,-1,1,1,3,3,3,4,6,7,2,0,0,2,2,2,1,77,39,130,53,2.91,1.06,3.98,1,1,1,1,0,0,1,1,0,0,1,0,1,0,1,16,11,-1,-1,-1,1,8,11,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,/clubs/brighton-hove-albion-fc-209,teams/england-brighton-hove-albion-fc.png,Brighton & Hove Albion,/clubs/luton-town-fc-271,teams/england-luton-town-fc.png,Luton Town,1.90,0.80,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,/england/brighton-hove-albion-fc-vs-luton-town...,9660,20,True,True,True,True,True,False,True,"['36', '71', '85', '90+5']",['81']
4,6688955,144,162,2023/2024,complete,100543,1,-1,[],['73'],0,1,1,10,4,14,6,3,0,2,0,0,10,3,6,6,16,9,12,6,41,59,705.0,197,214,Goodison Park (Liverpool),NaN,0,2,2.32,3.10,2.89,1.05,1.29,2.08,3.40,7.00,10.5,3.55,1.80,1.30,1.10,1.80,1.95,2.75,1.39,3.60,1.25,1.36,1.33,1.66,2.88,2.20,3.75,2.50,2.50,3.25,0,0,1.22,1.43,1.73,2.17,2.80,3.50,2.50,1.96,1.58,1.34,1.92,7.5,2.15,1.67,9.20,2.30,3.50,5.5,1.40,2.75,8.0,23,2.75,1.40,1.08,1.01,1.22,2.10,4.50,13.0,4.0,1.67,1.18,1.04,0,0,0,0,1,0,0,0,1,1,0,1691848800,162,0,0,0,0,0,-1,1,1,4,1,6,3,5,9,0,1,0,1,1,1,1,53,36,100,95,2.09,1.05,3.14,0,0,0,0,0,0,1,1,0,0,1,1,0,0,1,27,22,-1,-1,-1,1,10,6,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,/clubs/everton-fc-144,teams/england-everton-fc.png,Everton,/clubs/fulham-fc-162,teams/england-fulham-fc.png,Fulham,1.00,0.55,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,/england/everton-fc-vs-fulham-fc-h2h-stats#668...,9660,21,True,False,False,False,False,False,False,[],['73']

In [4]:
# read scraped testing data 
scraped_data = pd.read_csv('./data/scraped_testing_data.csv', header=0)

In [5]:
# inspect scraped testing data
scraped_data.head()

,id,title,h_a,xG,xGA,npxG,npxGA,deep,deep_allowed,scored,missed,xpts,result,date,wins,draws,loses,pts,npxGD,ppda.att,ppda.def,ppda_allowed.att,ppda_allowed.def
0,71,Aston Villa,a,1.486000,4.322080,1.486000,4.322080,6,9,1,5,0.1709,l,2023-08-12 16:30:00,0,0,1,0,-2.836080,324,28,255,17
1,71,Aston Villa,h,3.243360,0.721465,2.482190,0.721465,13,2,4,0,2.8069,w,2023-08-20 13:00:00,1,0,0,3,1.760725,204,12,385,23
2,71,Aston Villa,a,2.836910,0.630605,2.836910,0.630605,9,8,3,1,2.7695,w,2023-08-27 13:00:00,1,0,0,3,2.206305,365,15,254,31
3,71,Aston Villa,a,0.615503,2.731380,0.615503,2.731380,3,11,0,3,0.1952,l,2023-09-03 13:00:00,0,0,1,0,-2.115877,543,8,248,29
4,71,Aston Villa,h,2.315180,1.116960,1.554010,1.116960,14,7,3,1,2.2635,w,2023-09-16 14:00:00,1,0,0,3,0.437050,141,31,286,30

In [6]:
api_data['season'].unique()

array(['2023/2024'], dtype=object)

In [7]:
# Group the data by 'homeID' and get unique team names for each group
grouped_data = api_data.groupby('homeID')['home_name'].unique()

# Create a dictionary using zip
# - Explode the nested lists in 'home_name' to individual elements
# - Use zip to pair up each team name with its corresponding 'homeID'
# - Convert the pairs into a dictionary
team_id_mapping = dict(zip(grouped_data.explode(), grouped_data.index))

In [8]:
# view team mappings
print(team_id_mapping)

{'Arsenal': 59, 'Tottenham Hotspur': 92, 'Manchester City': 93, 'Crystal Palace': 143, 'Everton': 144, 'Burnley': 145, 'AFC Bournemouth': 148, 'Manchester United': 149, 'Liverpool': 151, 'Chelsea': 152, 'West Ham United': 153, 'Newcastle United': 157, 'Aston Villa': 158, 'Fulham': 162, 'Brighton & Hove Albion': 209, 'Nottingham Forest': 211, 'Brentford': 218, 'Wolverhampton Wanderers': 223, 'Sheffield United': 251, 'Luton Town': 271}

In [9]:
team_names_api_data = list(team_id_mapping.keys())

In [10]:
len(team_names_api_data)

20

In [11]:
team_names_scraped_data = scraped_data['title'].unique()

In [12]:
print(team_names_scraped_data)

['Aston Villa' 'Everton' 'Bournemouth' 'Crystal Palace' 'Chelsea'
 'West Ham' 'Tottenham' 'Arsenal' 'Newcastle United' 'Liverpool'
 'Manchester City' 'Manchester United' 'Burnley' 'Brighton' 'Fulham'
 'Wolverhampton Wanderers' 'Sheffield United' 'Brentford'
 'Nottingham Forest' 'Luton']

In [13]:
len(team_names_scraped_data)

20

In [14]:
# Get the teams that are in team_names_scraped_data but not in team_names_api_data
teams_not_in_api_data = [team for team in team_names_scraped_data if team not in team_names_api_data]

In [15]:
print(teams_not_in_api_data)

['Bournemouth', 'West Ham', 'Tottenham', 'Brighton', 'Luton']

## Harmonizing naming conventions

In [16]:
# Define a dictionary that maps original team names to their corresponding new names in the scraped_data 
names = {'West Ham': 'West Ham United', 'Tottenham': 'Tottenham Hotspur', 
         'Bournemouth': 'AFC Bournemouth','Brighton':'Brighton & Hove Albion', 'Luton':'Luton Town'}

In [17]:
# Replace names in the 'title' column
scraped_data['title'].replace(names, inplace=True)

In [18]:
# redefine team_names variable for scraped data
team_names_scraped_data = scraped_data['title'].unique()

In [19]:
# confirm renaming worked as planned
teams_not_in_api_data = [team for team in team_names_scraped_data if team not in team_names_api_data]

# there should be no naming mismatches
print(teams_not_in_api_data)

[]

## harmonize team_id columns
- Here we will adopt the team_ids from the api_data in the scraped_data dataframe
e

In [20]:
# Map team names to their corresponding teamID using the team_id_mapping dictionary
scraped_data['teamID'] = scraped_data['title'].map(team_id_mapping)

In [21]:
scraped_data.drop(columns=['id'], inplace=True)

In [22]:
scraped_data.head()

,title,h_a,xG,xGA,npxG,npxGA,deep,deep_allowed,scored,missed,xpts,result,date,wins,draws,loses,pts,npxGD,ppda.att,ppda.def,ppda_allowed.att,ppda_allowed.def,teamID
0,Aston Villa,a,1.486000,4.322080,1.486000,4.322080,6,9,1,5,0.1709,l,2023-08-12 16:30:00,0,0,1,0,-2.836080,324,28,255,17,158
1,Aston Villa,h,3.243360,0.721465,2.482190,0.721465,13,2,4,0,2.8069,w,2023-08-20 13:00:00,1,0,0,3,1.760725,204,12,385,23,158
2,Aston Villa,a,2.836910,0.630605,2.836910,0.630605,9,8,3,1,2.7695,w,2023-08-27 13:00:00,1,0,0,3,2.206305,365,15,254,31,158
3,Aston Villa,a,0.615503,2.731380,0.615503,2.731380,3,11,0,3,0.1952,l,2023-09-03 13:00:00,0,0,1,0,-2.115877,543,8,248,29,158
4,Aston Villa,h,2.315180,1.116960,1.554010,1.116960,14,7,3,1,2.2635,w,2023-09-16 14:00:00,1,0,0,3,0.437050,141,31,286,30,158

In [23]:
# Reorder columns with 'teamID' as the first column
scraped_data = scraped_data[['teamID', 'title', 'h_a', 'xG', 'xGA', 'npxG', 'npxGA', 'deep', 'deep_allowed',
                             'scored', 'missed', 'xpts', 'result', 'date', 'wins', 'draws', 'loses',
                             'pts', 'npxGD', 'ppda.att', 'ppda.def', 'ppda_allowed.att',
                             'ppda_allowed.def']]

In [24]:
scraped_data.head()

,teamID,title,h_a,xG,xGA,npxG,npxGA,deep,deep_allowed,scored,missed,xpts,result,date,wins,draws,loses,pts,npxGD,ppda.att,ppda.def,ppda_allowed.att,ppda_allowed.def
0,158,Aston Villa,a,1.486000,4.322080,1.486000,4.322080,6,9,1,5,0.1709,l,2023-08-12 16:30:00,0,0,1,0,-2.836080,324,28,255,17
1,158,Aston Villa,h,3.243360,0.721465,2.482190,0.721465,13,2,4,0,2.8069,w,2023-08-20 13:00:00,1,0,0,3,1.760725,204,12,385,23
2,158,Aston Villa,a,2.836910,0.630605,2.836910,0.630605,9,8,3,1,2.7695,w,2023-08-27 13:00:00,1,0,0,3,2.206305,365,15,254,31
3,158,Aston Villa,a,0.615503,2.731380,0.615503,2.731380,3,11,0,3,0.1952,l,2023-09-03 13:00:00,0,0,1,0,-2.115877,543,8,248,29
4,158,Aston Villa,h,2.315180,1.116960,1.554010,1.116960,14,7,3,1,2.2635,w,2023-09-16 14:00:00,1,0,0,3,0.437050,141,31,286,30

In [25]:
scraped_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 410 entries, 0 to 409
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   teamID            410 non-null    int64
 1   title             410 non-null    object
 2   h_a               410 non-null    object
 3   xG                410 non-null    float64
 4   xGA               410 non-null    float64
 5   npxG              410 non-null    float64
 6   npxGA             410 non-null    float64
 7   deep              410 non-null    int64
 8   deep_allowed      410 non-null    int64
 9   scored            410 non-null    int64
 10  missed            410 non-null    int64
 11  xpts              410 non-null    float64
 12  result            410 non-null    object
 13  date              410 non-null    object
 14  wins              410 non-null    int64
 15  draws             410 non-null    int64
 16  loses             410 non-null    int64
 17  pts               410 non-null    int64
 18  npxGD             410 non-null    float64
 19  ppda.att          410 non-null    int64
 20  ppda.def          410 non-null    int64
 21  ppda_allowed.att  410 non-null    int64
 22  ppda_allowed.def  410 non-null    int64
dtypes: float64(6), int64(13), object(4)
memory usage: 73.8+ KB

The date column was read as object instead of datetime, let's fix this.

In [26]:
# Convert 'date' column to datetime format
scraped_data['date'] = pd.to_datetime(scraped_data['date'])

In [27]:
# Extract the date part from the 'date' column
scraped_data['date'] = scraped_data['date'].dt.date

In [28]:
scraped_data[['date']].head()

         date
0  2023-08-12
1  2023-08-20
2  2023-08-27
3  2023-09-03
4  2023-09-16

In [29]:
scraped_data.to_csv('./data/cleaned_scraped_testing.csv', index=False)

In [30]:
# Convert the 'date_unix' column to datetime
api_data['date_unix'] = pd.to_datetime(api_data['date_unix'], unit='s')

In [31]:
api_data['date'] = api_data['date_unix'].dt.date

In [32]:
api_data[['date']].head()

         date
0  2023-08-11
1  2023-08-12
2  2023-08-12
3  2023-08-12
4  2023-08-12

### Data Aggregation:
With naming and date harmonization complete, we can now work on aggregating the two dataframes. We need only a few columns from the api_dataframe, we can drop the other columns.

In [33]:
# Keep only the specified columns in the api_data DataFrame
api_data_subset = api_data[['id', 'homeID','awayID', 'home_name', 'away_name', 'date', 'season', 'status', 'homeGoalCount', 'awayGoalCount',
                            'totalGoalCount', 'team_a_cards_num', 'team_b_cards_num', 'odds_ft_1', 'odds_ft_x',
                            'odds_ft_2', 'home_ppg', 'away_ppg', 'team_a_xg_prematch', 'team_b_xg_prematch',
                            'total_xg_prematch', ]]

In [34]:
api_data_subset.head()

,id,homeID,awayID,home_name,away_name,date,season,status,homeGoalCount,awayGoalCount,totalGoalCount,team_a_cards_num,team_b_cards_num,odds_ft_1,odds_ft_x,odds_ft_2,home_ppg,away_ppg,team_a_xg_prematch,team_b_xg_prematch,total_xg_prematch
0,6688951,145,93,Burnley,Manchester City,2023-08-11,2023/2024,complete,0,3,3,2,0,11.00,6.30,1.28,0.36,2.00,0.0,0.0,0.0
1,6688952,59,211,Arsenal,Nottingham Forest,2023-08-12,2023/2024,complete,2,1,3,2,2,1.25,6.25,9.50,2.36,0.73,0.0,0.0,0.0
2,6688953,148,153,AFC Bournemouth,West Ham United,2023-08-12,2023/2024,complete,1,1,2,1,4,2.63,3.06,2.35,1.33,1.60,0.0,0.0,0.0
3,6688954,209,271,Brighton & Hove Albion,Luton Town,2023-08-12,2023/2024,complete,4,1,5,2,2,1.34,4.70,7.00,1.90,0.80,0.0,0.0,0.0
4,6688955,144,162,Everton,Fulham,2023-08-12,2023/2024,complete,0,1,1,0,2,2.32,3.10,2.89,1.00,0.55,0.0,0.0,0.0

In [35]:
# Define a list of features from the 'scraped_data' dataframe to include in the merged dataframe
scraped_data_feats = ['xG', 'xGA', 'npxG', 'npxGA', 'deep', 'deep_allowed', 'scored', 'missed', 
                      'xpts', 'npxGD', 'ppda.att', 'ppda.def', 'ppda_allowed.att', 'ppda_allowed.def']

In [36]:
# Create empty columns for home and away features
for feat in scraped_data_feats:
    api_data_subset[f'{feat}_home'] = None
    api_data_subset[f'{feat}_away'] = None

C:\Users\user\AppData\Local\Temp\ipykernel_10340\1963605939.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset[f'{feat}_home'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_10340\1963605939.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset[f'{feat}_away'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_10340\1963605939.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset[f'{feat}_home'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_10340\1963605939.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset[f'{feat}_away'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_10340\1963605939.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset[f'{feat}_home'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_10340\1963605939.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset[f'{feat}_away'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_10340\1963605939.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset[f'{feat}_home'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_10340\1963605939.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset[f'{feat}_away'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_10340\1963605939.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset[f'{feat}_home'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_10340\1963605939.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset[f'{feat}_away'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_10340\1963605939.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset[f'{feat}_home'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_10340\1963605939.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset[f'{feat}_away'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_10340\1963605939.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset[f'{feat}_home'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_10340\1963605939.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset[f'{feat}_away'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_10340\1963605939.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset[f'{feat}_home'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_10340\1963605939.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset[f'{feat}_away'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_10340\1963605939.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset[f'{feat}_home'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_10340\1963605939.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset[f'{feat}_away'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_10340\1963605939.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset[f'{feat}_home'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_10340\1963605939.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset[f'{feat}_away'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_10340\1963605939.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset[f'{feat}_home'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_10340\1963605939.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset[f'{feat}_away'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_10340\1963605939.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset[f'{feat}_home'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_10340\1963605939.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset[f'{feat}_away'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_10340\1963605939.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset[f'{feat}_home'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_10340\1963605939.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset[f'{feat}_away'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_10340\1963605939.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset[f'{feat}_home'] = None
C:\Users\user\AppData\Local\Temp\ipykernel_10340\1963605939.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  api_data_subset[f'{feat}_away'] = None

In [37]:
api_data_subset.head()

,id,homeID,awayID,home_name,away_name,date,season,status,homeGoalCount,awayGoalCount,totalGoalCount,team_a_cards_num,team_b_cards_num,odds_ft_1,odds_ft_x,odds_ft_2,home_ppg,away_ppg,team_a_xg_prematch,team_b_xg_prematch,total_xg_prematch,xG_home,xG_away,xGA_home,xGA_away,npxG_home,npxG_away,npxGA_home,npxGA_away,deep_home,deep_away,deep_allowed_home,deep_allowed_away,scored_home,scored_away,missed_home,missed_away,xpts_home,xpts_away,npxGD_home,npxGD_away,ppda.att_home,ppda.att_away,ppda.def_home,ppda.def_away,ppda_allowed.att_home,ppda_allowed.att_away,ppda_allowed.def_home,ppda_allowed.def_away
0,6688951,145,93,Burnley,Manchester City,2023-08-11,2023/2024,complete,0,3,3,2,0,11.00,6.30,1.28,0.36,2.00,0.0,0.0,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1,6688952,59,211,Arsenal,Nottingham Forest,2023-08-12,2023/2024,complete,2,1,3,2,2,1.25,6.25,9.50,2.36,0.73,0.0,0.0,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2,6688953,148,153,AFC Bournemouth,West Ham United,2023-08-12,2023/2024,complete,1,1,2,1,4,2.63,3.06,2.35,1.33,1.60,0.0,0.0,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3,6688954,209,271,Brighton & Hove Albion,Luton Town,2023-08-12,2023/2024,complete,4,1,5,2,2,1.34,4.70,7.00,1.90,0.80,0.0,0.0,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
4,6688955,144,162,Everton,Fulham,2023-08-12,2023/2024,complete,0,1,1,0,2,2.32,3.10,2.89,1.00,0.55,0.0,0.0,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

In [38]:
# Iterate through each row in api_data_subset
for index, row in api_data_subset.iterrows():
    home_id = row['homeID']
    game_date = row['date']
    
    # Retrieve stats from scraped_data dataframe
    result = scraped_data[(scraped_data['teamID'] == home_id) & (scraped_data['date'] == game_date)]
    
    # Check if there are matching records
    if not result.empty:
        # Take the first matching record
        filtered_result_dict = result.iloc[0].to_dict()
        
        # Filter out irrelevant columns from result
        filtered_result_dict = {key: value for key, value in filtered_result_dict.items() if key in scraped_data_feats}
        
        # Update values in the dataframe
        for key, value in filtered_result_dict.items():
            api_data_subset.at[index, f'{key}_home'] = value

In [39]:
# Iterate through each row in api_data_subset
for index, row in api_data_subset.iterrows():
    home_id = row['awayID']
    game_date = row['date']
    
    # Retrieve stats from scraped_data dataframe
    result = scraped_data[(scraped_data['teamID'] == home_id) & (scraped_data['date'] == game_date)]
    
    # Check if there are matching records
    if not result.empty:
        # Take the first matching record
        filtered_result_dict = result.iloc[0].to_dict()
        
        # Filter out irrelevant columns from result
        filtered_result_dict = {key: value for key, value in filtered_result_dict.items() if key in scraped_data_feats}
        
        # Update values in the dataframe
        for key, value in filtered_result_dict.items():
            api_data_subset.at[index, f'{key}_away'] = value

In [40]:
# Inspect the resulting dataframe
api_data_subset.head()

,id,homeID,awayID,home_name,away_name,date,season,status,homeGoalCount,awayGoalCount,totalGoalCount,team_a_cards_num,team_b_cards_num,odds_ft_1,odds_ft_x,odds_ft_2,home_ppg,away_ppg,team_a_xg_prematch,team_b_xg_prematch,total_xg_prematch,xG_home,xG_away,xGA_home,xGA_away,npxG_home,npxG_away,npxGA_home,npxGA_away,deep_home,deep_away,deep_allowed_home,deep_allowed_away,scored_home,scored_away,missed_home,missed_away,xpts_home,xpts_away,npxGD_home,npxGD_away,ppda.att_home,ppda.att_away,ppda.def_home,ppda.def_away,ppda_allowed.att_home,ppda_allowed.att_away,ppda_allowed.def_home,ppda_allowed.def_away
0,6688951,145,93,Burnley,Manchester City,2023-08-11,2023/2024,complete,0,3,3,2,0,11.00,6.30,1.28,0.36,2.00,0.0,0.0,0.0,0.311032,2.40074,2.40074,0.311032,0.311032,2.40074,2.40074,0.311032,4,9,9,4,0,3,3,0,0.1385,2.7761,-2.089708,2.089708,463,237,14,15,237,463,15,14
1,6688952,59,211,Arsenal,Nottingham Forest,2023-08-12,2023/2024,complete,2,1,3,2,2,1.25,6.25,9.50,2.36,0.73,0.0,0.0,0.0,0.84262,0.966305,0.966305,0.84262,0.84262,0.966305,0.966305,0.84262,9,4,4,9,2,1,1,2,1.1754,1.4883,-0.123685,0.123685,108,441,27,10,441,108,10,27
2,6688953,148,153,AFC Bournemouth,West Ham United,2023-08-12,2023/2024,complete,1,1,2,1,4,2.63,3.06,2.35,1.33,1.60,0.0,0.0,0.0,1.51025,1.4834,1.4834,1.51025,1.51025,1.4834,1.4834,1.51025,9,8,8,9,1,1,1,1,1.3846,1.2985,0.02685,-0.02685,138,292,27,30,292,138,30,27
3,6688954,209,271,Brighton & Hove Albion,Luton Town,2023-08-12,2023/2024,complete,4,1,5,2,2,1.34,4.70,7.00,1.90,0.80,0.0,0.0,0.0,4.36748,1.88594,1.88594,4.36748,3.60631,1.12477,1.12477,3.60631,17,5,5,17,4,1,1,4,2.7246,0.1878,2.48154,-2.48154,110,369,16,16,369,110,16,16
4,6688955,144,162,Everton,Fulham,2023-08-12,2023/2024,complete,0,1,1,0,2,2.32,3.10,2.89,1.00,0.55,0.0,0.0,0.0,2.59001,1.58144,1.58144,2.59001,2.59001,1.58144,1.58144,2.59001,7,6,6,7,0,1,1,0,2.1102,0.6909,1.00857,-1.00857,341,174,23,10,174,341,10,23

In [41]:
api_data_subset.to_csv('./data/aggredated_testing_data.csv', index=False)